title: Moving in the Scene view
hero_image: images/banner.png
description: unity-scene-moving description
version: 4
listed: false
copyedit: false
last_tested: "2021-11-17"
steps:
  - title: Moving in the Scene view

